/*
Copyright 2025 The Apex Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import {
  BaseVisitor,
  Context,
  Visitor,
  Writer,
} from "../../deps/@apexlang/core/model/mod.ts";
import { TypeVisitor } from "./types_visitor.ts";
import { InterfaceVisitor } from "./interface_visitor.ts";
import { parseNamespaceName } from "./helpers.ts";
import { EnumVisitor } from "./enum_visitor.ts";
import { UnionVisitor } from "./union_visitor.ts";
import { AliasVisitor } from "./alias_visitor.ts";

export class InterfacesVisitor extends BaseVisitor {
  typeVisitor = (writer: Writer): Visitor => new TypeVisitor(writer);
  interfaceVisitor = (writer: Writer): Visitor => new InterfaceVisitor(writer);
  enumVisitor = (writer: Writer): Visitor => new EnumVisitor(writer);
  unionVisitor = (writer: Writer): Visitor => new UnionVisitor(writer);
  aliasVisitor = (writer: Writer): Visitor => new AliasVisitor(writer);

  public override visitNamespaceBefore(context: Context) {
    this.write(`// Code generated by @apexlang/codegen. DO NOT EDIT.\n\n`);
    super.visitNamespaceBefore(context);
  }

  public override visitNamespace(context: Context) {
    this.write(`namespace ${parseNamespaceName(context.namespace.name)} {\n`);
    super.visitNamespace(context);
  }

  public override visitNamespaceAfter(context: Context) {
    this.write(`}\n`);
    super.visitNamespaceAfter(context);
  }

  public override visitInterface(context: Context) {
    const visitor = this.interfaceVisitor(this.writer);
    context.interface.accept(context, visitor);
  }

  public override visitUnion(context: Context) {
    const visitor = this.unionVisitor(this.writer);
    context.union.accept(context, visitor);
  }

  public override visitAlias(context: Context) {
    const visitor = this.aliasVisitor(this.writer);
    context.alias.accept(context, visitor);
  }

  public override visitEnum(context: Context): void {
    const visitor = this.enumVisitor(this.writer);
    context.enum.accept(context, visitor);
  }

  public override visitType(context: Context) {
    const visitor = this.typeVisitor(this.writer);
    context.type.accept(context, visitor);
  }
}
