// Code generated by @apexlang/codegen. DO NOT EDIT.

package outputtest

import (
	"github.com/google/uuid"
	"github.com/wapc/tinygo-msgpack"
	"github.com/wapc/tinygo-msgpack/convert"
)

type MyServiceFuncTypeArgs struct {
	Value    MyType  `json:"value" yaml:"value" msgpack:"value"`
	Optional *MyType `json:"optional,omitempty" yaml:"optional,omitempty" msgpack:"optional,omitempty"`
}

func (o *MyServiceFuncTypeArgs) Decode(decoder msgpack.Reader) error {
	numFields, err := decoder.ReadMapSize()
	if err != nil {
		return err
	}

	var _o MyServiceFuncTypeArgs
	for numFields > 0 {
		numFields--
		field, err := decoder.ReadString()
		if err != nil {
			return err
		}
		switch field {
		case "value":
			err = _o.Value.Decode(decoder)
		case "optional":
			_o.Optional, err = msgpack.DecodeNillable[MyType](decoder)
		default:
			err = decoder.Skip()
		}
		if err != nil {
			return err
		}
		*o = _o
	}

	return nil
}

func (o *MyServiceFuncTypeArgs) Encode(encoder msgpack.Writer) error {
	if o == nil {
		encoder.WriteNil()
		return nil
	}
	encoder.WriteMapSize(2)
	encoder.WriteString("value")
	o.Value.Encode(encoder)
	encoder.WriteString("optional")
	o.Optional.Encode(encoder)

	return nil
}

type MyServiceFuncEnumArgs struct {
	Value    MyEnum  `json:"value" yaml:"value" msgpack:"value"`
	Optional *MyEnum `json:"optional,omitempty" yaml:"optional,omitempty" msgpack:"optional,omitempty"`
}

func (o *MyServiceFuncEnumArgs) Decode(decoder msgpack.Reader) error {
	numFields, err := decoder.ReadMapSize()
	if err != nil {
		return err
	}

	var _o MyServiceFuncEnumArgs
	for numFields > 0 {
		numFields--
		field, err := decoder.ReadString()
		if err != nil {
			return err
		}
		switch field {
		case "value":
			_o.Value, err = convert.Numeric[MyEnum](decoder.ReadInt32())
		case "optional":
			_o.Optional, err = convert.NillableNumeric[MyEnum](decoder.ReadNillableInt32())
		default:
			err = decoder.Skip()
		}
		if err != nil {
			return err
		}
		*o = _o
	}

	return nil
}

func (o *MyServiceFuncEnumArgs) Encode(encoder msgpack.Writer) error {
	if o == nil {
		encoder.WriteNil()
		return nil
	}
	encoder.WriteMapSize(2)
	encoder.WriteString("value")
	encoder.WriteInt32(int32(o.Value))
	encoder.WriteString("optional")
	encoder.WriteNillableInt32((*int32)(o.Optional))

	return nil
}

type MyServiceFuncAliasArgs struct {
	Value    uuid.UUID  `json:"value" yaml:"value" msgpack:"value"`
	Optional *uuid.UUID `json:"optional,omitempty" yaml:"optional,omitempty" msgpack:"optional,omitempty"`
}

func (o *MyServiceFuncAliasArgs) Decode(decoder msgpack.Reader) error {
	numFields, err := decoder.ReadMapSize()
	if err != nil {
		return err
	}

	var _o MyServiceFuncAliasArgs
	for numFields > 0 {
		numFields--
		field, err := decoder.ReadString()
		if err != nil {
			return err
		}
		switch field {
		case "value":
			_o.Value, err = convert.Parse(uuid.Parse)(decoder.ReadString())
		case "optional":
			_o.Optional, err = convert.NillableParse(uuid.Parse)(decoder.ReadNillableString())
		default:
			err = decoder.Skip()
		}
		if err != nil {
			return err
		}
		*o = _o
	}

	return nil
}

func (o *MyServiceFuncAliasArgs) Encode(encoder msgpack.Writer) error {
	if o == nil {
		encoder.WriteNil()
		return nil
	}
	encoder.WriteMapSize(2)
	encoder.WriteString("value")
	encoder.WriteString(o.Value.String())
	encoder.WriteString("optional")
	if o.Optional == nil {
		encoder.WriteNil()
	} else {
		encoder.WriteString(o.Optional.String())
	}

	return nil
}

type MyServiceFuncStringArgs struct {
	Value    string  `json:"value" yaml:"value" msgpack:"value"`
	Optional *string `json:"optional,omitempty" yaml:"optional,omitempty" msgpack:"optional,omitempty"`
}

func (o *MyServiceFuncStringArgs) Decode(decoder msgpack.Reader) error {
	numFields, err := decoder.ReadMapSize()
	if err != nil {
		return err
	}

	var _o MyServiceFuncStringArgs
	for numFields > 0 {
		numFields--
		field, err := decoder.ReadString()
		if err != nil {
			return err
		}
		switch field {
		case "value":
			_o.Value, err = decoder.ReadString()
		case "optional":
			_o.Optional, err = decoder.ReadNillableString()
		default:
			err = decoder.Skip()
		}
		if err != nil {
			return err
		}
		*o = _o
	}

	return nil
}

func (o *MyServiceFuncStringArgs) Encode(encoder msgpack.Writer) error {
	if o == nil {
		encoder.WriteNil()
		return nil
	}
	encoder.WriteMapSize(2)
	encoder.WriteString("value")
	encoder.WriteString(o.Value)
	encoder.WriteString("optional")
	encoder.WriteNillableString(o.Optional)

	return nil
}

type MyServiceFuncI64Args struct {
	Value    int64  `json:"value" yaml:"value" msgpack:"value"`
	Optional *int64 `json:"optional,omitempty" yaml:"optional,omitempty" msgpack:"optional,omitempty"`
}

func (o *MyServiceFuncI64Args) Decode(decoder msgpack.Reader) error {
	numFields, err := decoder.ReadMapSize()
	if err != nil {
		return err
	}

	var _o MyServiceFuncI64Args
	for numFields > 0 {
		numFields--
		field, err := decoder.ReadString()
		if err != nil {
			return err
		}
		switch field {
		case "value":
			_o.Value, err = decoder.ReadInt64()
		case "optional":
			_o.Optional, err = decoder.ReadNillableInt64()
		default:
			err = decoder.Skip()
		}
		if err != nil {
			return err
		}
		*o = _o
	}

	return nil
}

func (o *MyServiceFuncI64Args) Encode(encoder msgpack.Writer) error {
	if o == nil {
		encoder.WriteNil()
		return nil
	}
	encoder.WriteMapSize(2)
	encoder.WriteString("value")
	encoder.WriteInt64(o.Value)
	encoder.WriteString("optional")
	encoder.WriteNillableInt64(o.Optional)

	return nil
}

type MyServiceFuncI32Args struct {
	Value    int32  `json:"value" yaml:"value" msgpack:"value"`
	Optional *int32 `json:"optional,omitempty" yaml:"optional,omitempty" msgpack:"optional,omitempty"`
}

func (o *MyServiceFuncI32Args) Decode(decoder msgpack.Reader) error {
	numFields, err := decoder.ReadMapSize()
	if err != nil {
		return err
	}

	var _o MyServiceFuncI32Args
	for numFields > 0 {
		numFields--
		field, err := decoder.ReadString()
		if err != nil {
			return err
		}
		switch field {
		case "value":
			_o.Value, err = decoder.ReadInt32()
		case "optional":
			_o.Optional, err = decoder.ReadNillableInt32()
		default:
			err = decoder.Skip()
		}
		if err != nil {
			return err
		}
		*o = _o
	}

	return nil
}

func (o *MyServiceFuncI32Args) Encode(encoder msgpack.Writer) error {
	if o == nil {
		encoder.WriteNil()
		return nil
	}
	encoder.WriteMapSize(2)
	encoder.WriteString("value")
	encoder.WriteInt32(o.Value)
	encoder.WriteString("optional")
	encoder.WriteNillableInt32(o.Optional)

	return nil
}

type MyServiceFuncI16Args struct {
	Value    int16  `json:"value" yaml:"value" msgpack:"value"`
	Optional *int16 `json:"optional,omitempty" yaml:"optional,omitempty" msgpack:"optional,omitempty"`
}

func (o *MyServiceFuncI16Args) Decode(decoder msgpack.Reader) error {
	numFields, err := decoder.ReadMapSize()
	if err != nil {
		return err
	}

	var _o MyServiceFuncI16Args
	for numFields > 0 {
		numFields--
		field, err := decoder.ReadString()
		if err != nil {
			return err
		}
		switch field {
		case "value":
			_o.Value, err = decoder.ReadInt16()
		case "optional":
			_o.Optional, err = decoder.ReadNillableInt16()
		default:
			err = decoder.Skip()
		}
		if err != nil {
			return err
		}
		*o = _o
	}

	return nil
}

func (o *MyServiceFuncI16Args) Encode(encoder msgpack.Writer) error {
	if o == nil {
		encoder.WriteNil()
		return nil
	}
	encoder.WriteMapSize(2)
	encoder.WriteString("value")
	encoder.WriteInt16(o.Value)
	encoder.WriteString("optional")
	encoder.WriteNillableInt16(o.Optional)

	return nil
}

type MyServiceFuncI8Args struct {
	Value    int8  `json:"value" yaml:"value" msgpack:"value"`
	Optional *int8 `json:"optional,omitempty" yaml:"optional,omitempty" msgpack:"optional,omitempty"`
}

func (o *MyServiceFuncI8Args) Decode(decoder msgpack.Reader) error {
	numFields, err := decoder.ReadMapSize()
	if err != nil {
		return err
	}

	var _o MyServiceFuncI8Args
	for numFields > 0 {
		numFields--
		field, err := decoder.ReadString()
		if err != nil {
			return err
		}
		switch field {
		case "value":
			_o.Value, err = decoder.ReadInt8()
		case "optional":
			_o.Optional, err = decoder.ReadNillableInt8()
		default:
			err = decoder.Skip()
		}
		if err != nil {
			return err
		}
		*o = _o
	}

	return nil
}

func (o *MyServiceFuncI8Args) Encode(encoder msgpack.Writer) error {
	if o == nil {
		encoder.WriteNil()
		return nil
	}
	encoder.WriteMapSize(2)
	encoder.WriteString("value")
	encoder.WriteInt8(o.Value)
	encoder.WriteString("optional")
	encoder.WriteNillableInt8(o.Optional)

	return nil
}

type MyServiceFuncU64Args struct {
	Value    uint64  `json:"value" yaml:"value" msgpack:"value"`
	Optional *uint64 `json:"optional,omitempty" yaml:"optional,omitempty" msgpack:"optional,omitempty"`
}

func (o *MyServiceFuncU64Args) Decode(decoder msgpack.Reader) error {
	numFields, err := decoder.ReadMapSize()
	if err != nil {
		return err
	}

	var _o MyServiceFuncU64Args
	for numFields > 0 {
		numFields--
		field, err := decoder.ReadString()
		if err != nil {
			return err
		}
		switch field {
		case "value":
			_o.Value, err = decoder.ReadUint64()
		case "optional":
			_o.Optional, err = decoder.ReadNillableUint64()
		default:
			err = decoder.Skip()
		}
		if err != nil {
			return err
		}
		*o = _o
	}

	return nil
}

func (o *MyServiceFuncU64Args) Encode(encoder msgpack.Writer) error {
	if o == nil {
		encoder.WriteNil()
		return nil
	}
	encoder.WriteMapSize(2)
	encoder.WriteString("value")
	encoder.WriteUint64(o.Value)
	encoder.WriteString("optional")
	encoder.WriteNillableUint64(o.Optional)

	return nil
}

type MyServiceFuncU32Args struct {
	Value    uint32  `json:"value" yaml:"value" msgpack:"value"`
	Optional *uint32 `json:"optional,omitempty" yaml:"optional,omitempty" msgpack:"optional,omitempty"`
}

func (o *MyServiceFuncU32Args) Decode(decoder msgpack.Reader) error {
	numFields, err := decoder.ReadMapSize()
	if err != nil {
		return err
	}

	var _o MyServiceFuncU32Args
	for numFields > 0 {
		numFields--
		field, err := decoder.ReadString()
		if err != nil {
			return err
		}
		switch field {
		case "value":
			_o.Value, err = decoder.ReadUint32()
		case "optional":
			_o.Optional, err = decoder.ReadNillableUint32()
		default:
			err = decoder.Skip()
		}
		if err != nil {
			return err
		}
		*o = _o
	}

	return nil
}

func (o *MyServiceFuncU32Args) Encode(encoder msgpack.Writer) error {
	if o == nil {
		encoder.WriteNil()
		return nil
	}
	encoder.WriteMapSize(2)
	encoder.WriteString("value")
	encoder.WriteUint32(o.Value)
	encoder.WriteString("optional")
	encoder.WriteNillableUint32(o.Optional)

	return nil
}

type MyServiceFuncU16Args struct {
	Value    uint16  `json:"value" yaml:"value" msgpack:"value"`
	Optional *uint16 `json:"optional,omitempty" yaml:"optional,omitempty" msgpack:"optional,omitempty"`
}

func (o *MyServiceFuncU16Args) Decode(decoder msgpack.Reader) error {
	numFields, err := decoder.ReadMapSize()
	if err != nil {
		return err
	}

	var _o MyServiceFuncU16Args
	for numFields > 0 {
		numFields--
		field, err := decoder.ReadString()
		if err != nil {
			return err
		}
		switch field {
		case "value":
			_o.Value, err = decoder.ReadUint16()
		case "optional":
			_o.Optional, err = decoder.ReadNillableUint16()
		default:
			err = decoder.Skip()
		}
		if err != nil {
			return err
		}
		*o = _o
	}

	return nil
}

func (o *MyServiceFuncU16Args) Encode(encoder msgpack.Writer) error {
	if o == nil {
		encoder.WriteNil()
		return nil
	}
	encoder.WriteMapSize(2)
	encoder.WriteString("value")
	encoder.WriteUint16(o.Value)
	encoder.WriteString("optional")
	encoder.WriteNillableUint16(o.Optional)

	return nil
}

type MyServiceFuncU8Args struct {
	Value    uint8  `json:"value" yaml:"value" msgpack:"value"`
	Optional *uint8 `json:"optional,omitempty" yaml:"optional,omitempty" msgpack:"optional,omitempty"`
}

func (o *MyServiceFuncU8Args) Decode(decoder msgpack.Reader) error {
	numFields, err := decoder.ReadMapSize()
	if err != nil {
		return err
	}

	var _o MyServiceFuncU8Args
	for numFields > 0 {
		numFields--
		field, err := decoder.ReadString()
		if err != nil {
			return err
		}
		switch field {
		case "value":
			_o.Value, err = decoder.ReadUint8()
		case "optional":
			_o.Optional, err = decoder.ReadNillableUint8()
		default:
			err = decoder.Skip()
		}
		if err != nil {
			return err
		}
		*o = _o
	}

	return nil
}

func (o *MyServiceFuncU8Args) Encode(encoder msgpack.Writer) error {
	if o == nil {
		encoder.WriteNil()
		return nil
	}
	encoder.WriteMapSize(2)
	encoder.WriteString("value")
	encoder.WriteUint8(o.Value)
	encoder.WriteString("optional")
	encoder.WriteNillableUint8(o.Optional)

	return nil
}

type MyServiceFuncF64Args struct {
	Value    float64  `json:"value" yaml:"value" msgpack:"value"`
	Optional *float64 `json:"optional,omitempty" yaml:"optional,omitempty" msgpack:"optional,omitempty"`
}

func (o *MyServiceFuncF64Args) Decode(decoder msgpack.Reader) error {
	numFields, err := decoder.ReadMapSize()
	if err != nil {
		return err
	}

	var _o MyServiceFuncF64Args
	for numFields > 0 {
		numFields--
		field, err := decoder.ReadString()
		if err != nil {
			return err
		}
		switch field {
		case "value":
			_o.Value, err = decoder.ReadFloat64()
		case "optional":
			_o.Optional, err = decoder.ReadNillableFloat64()
		default:
			err = decoder.Skip()
		}
		if err != nil {
			return err
		}
		*o = _o
	}

	return nil
}

func (o *MyServiceFuncF64Args) Encode(encoder msgpack.Writer) error {
	if o == nil {
		encoder.WriteNil()
		return nil
	}
	encoder.WriteMapSize(2)
	encoder.WriteString("value")
	encoder.WriteFloat64(o.Value)
	encoder.WriteString("optional")
	encoder.WriteNillableFloat64(o.Optional)

	return nil
}

type MyServiceFuncF32Args struct {
	Value    float32  `json:"value" yaml:"value" msgpack:"value"`
	Optional *float32 `json:"optional,omitempty" yaml:"optional,omitempty" msgpack:"optional,omitempty"`
}

func (o *MyServiceFuncF32Args) Decode(decoder msgpack.Reader) error {
	numFields, err := decoder.ReadMapSize()
	if err != nil {
		return err
	}

	var _o MyServiceFuncF32Args
	for numFields > 0 {
		numFields--
		field, err := decoder.ReadString()
		if err != nil {
			return err
		}
		switch field {
		case "value":
			_o.Value, err = decoder.ReadFloat32()
		case "optional":
			_o.Optional, err = decoder.ReadNillableFloat32()
		default:
			err = decoder.Skip()
		}
		if err != nil {
			return err
		}
		*o = _o
	}

	return nil
}

func (o *MyServiceFuncF32Args) Encode(encoder msgpack.Writer) error {
	if o == nil {
		encoder.WriteNil()
		return nil
	}
	encoder.WriteMapSize(2)
	encoder.WriteString("value")
	encoder.WriteFloat32(o.Value)
	encoder.WriteString("optional")
	encoder.WriteNillableFloat32(o.Optional)

	return nil
}

type MyServiceFuncBytesArgs struct {
	Value    []byte `json:"value" yaml:"value" msgpack:"value"`
	Optional []byte `json:"optional,omitempty" yaml:"optional,omitempty" msgpack:"optional,omitempty"`
}

func (o *MyServiceFuncBytesArgs) Decode(decoder msgpack.Reader) error {
	numFields, err := decoder.ReadMapSize()
	if err != nil {
		return err
	}

	var _o MyServiceFuncBytesArgs
	for numFields > 0 {
		numFields--
		field, err := decoder.ReadString()
		if err != nil {
			return err
		}
		switch field {
		case "value":
			_o.Value, err = decoder.ReadByteArray()
		case "optional":
			_o.Optional, err = decoder.ReadNillableByteArray()
		default:
			err = decoder.Skip()
		}
		if err != nil {
			return err
		}
		*o = _o
	}

	return nil
}

func (o *MyServiceFuncBytesArgs) Encode(encoder msgpack.Writer) error {
	if o == nil {
		encoder.WriteNil()
		return nil
	}
	encoder.WriteMapSize(2)
	encoder.WriteString("value")
	encoder.WriteByteArray(o.Value)
	encoder.WriteString("optional")
	encoder.WriteNillableByteArray(o.Optional)

	return nil
}

func (o *MyType) Decode(decoder msgpack.Reader) error {
	numFields, err := decoder.ReadMapSize()
	if err != nil {
		return err
	}

	var _o MyType
	for numFields > 0 {
		numFields--
		field, err := decoder.ReadString()
		if err != nil {
			return err
		}
		switch field {
		case "sameValue":
			_o.SameValue, err = msgpack.DecodeNillable[MyType](decoder)
		case "typeValue":
			err = _o.TypeValue.Decode(decoder)
		case "stringValue":
			_o.StringValue, err = decoder.ReadString()
		case "stringOption":
			_o.StringOption, err = decoder.ReadNillableString()
		case "i64Value":
			_o.I64Value, err = decoder.ReadInt64()
		case "i64Option":
			_o.I64Option, err = decoder.ReadNillableInt64()
		case "i32Value":
			_o.I32Value, err = decoder.ReadInt32()
		case "i32Option":
			_o.I32Option, err = decoder.ReadNillableInt32()
		case "i16Value":
			_o.I16Value, err = decoder.ReadInt16()
		case "i16Option":
			_o.I16Option, err = decoder.ReadNillableInt16()
		case "i8Value":
			_o.I8Value, err = decoder.ReadInt8()
		case "i8Option":
			_o.I8Option, err = decoder.ReadNillableInt8()
		case "u64Value":
			_o.U64Value, err = decoder.ReadUint64()
		case "u64Option":
			_o.U64Option, err = decoder.ReadNillableUint64()
		case "u32Value":
			_o.U32Value, err = decoder.ReadUint32()
		case "u32Option":
			_o.U32Option, err = decoder.ReadNillableUint32()
		case "u16Value":
			_o.U16Value, err = decoder.ReadUint16()
		case "u16Option":
			_o.U16Option, err = decoder.ReadNillableUint16()
		case "u8Value":
			_o.U8Value, err = decoder.ReadUint8()
		case "u8Option":
			_o.U8Option, err = decoder.ReadNillableUint8()
		case "f64Value":
			_o.F64Value, err = decoder.ReadFloat64()
		case "f64Option":
			_o.F64Option, err = decoder.ReadNillableFloat64()
		case "f32Value":
			_o.F32Value, err = decoder.ReadFloat32()
		case "f32Option":
			_o.F32Option, err = decoder.ReadNillableFloat32()
		case "datetimeValue":
			_o.DatetimeValue, err = decoder.ReadTime()
		case "datetimeOption":
			_o.DatetimeOption, err = decoder.ReadNillableTime()
		case "bytesValue":
			_o.BytesValue, err = decoder.ReadByteArray()
		case "bytesOption":
			_o.BytesOption, err = decoder.ReadNillableByteArray()
		case "mapValue":
			mapSize, err := decoder.ReadMapSize()
			if err != nil {
				return err
			}
			_o.MapValue = make(map[string]int64, mapSize)
			for mapSize > 0 {
				mapSize--
				key, err := decoder.ReadString()
				if err != nil {
					return err
				}
				value, err := decoder.ReadInt64()
				if err != nil {
					return err
				}
				_o.MapValue[key] = value
			}
		case "mapOfTypes":
			mapSize, err := decoder.ReadMapSize()
			if err != nil {
				return err
			}
			_o.MapOfTypes = make(map[string]MyType, mapSize)
			for mapSize > 0 {
				mapSize--
				key, err := decoder.ReadString()
				if err != nil {
					return err
				}
				value, err := msgpack.Decode[MyType](decoder)
				if err != nil {
					return err
				}
				_o.MapOfTypes[key] = value
			}
		case "arrayValue":
			listSize, err := decoder.ReadArraySize()
			if err != nil {
				return err
			}
			_o.ArrayValue = make([]string, 0, listSize)
			for listSize > 0 {
				listSize--
				var nonNilItem string
				nonNilItem, err = decoder.ReadString()
				if err != nil {
					return err
				}
				_o.ArrayValue = append(_o.ArrayValue, nonNilItem)
			}
		case "arrayOfTypes":
			listSize, err := decoder.ReadArraySize()
			if err != nil {
				return err
			}
			_o.ArrayOfTypes = make([]MyType, 0, listSize)
			for listSize > 0 {
				listSize--
				var nonNilItem MyType
				err = nonNilItem.Decode(decoder)
				if err != nil {
					return err
				}
				_o.ArrayOfTypes = append(_o.ArrayOfTypes, nonNilItem)
			}
		case "unionValue":
			_o.UnionValue, err = msgpack.Decode[MyUnion](decoder)
		case "unionOption":
			_o.UnionOption, err = msgpack.DecodeNillable[MyUnion](decoder)
		case "enumValue":
			_o.EnumValue, err = convert.Numeric[MyEnum](decoder.ReadInt32())
		case "enumOption":
			_o.EnumOption, err = convert.NillableNumeric[MyEnum](decoder.ReadNillableInt32())
		case "aliasValue":
			_o.AliasValue, err = convert.Parse(uuid.Parse)(decoder.ReadString())
		case "aliasOption":
			_o.AliasOption, err = convert.NillableParse(uuid.Parse)(decoder.ReadNillableString())
		case "boolValue":
			_o.BoolValue, err = decoder.ReadBool()
		case "boolOption":
			_o.BoolOption, err = decoder.ReadNillableBool()
		default:
			err = decoder.Skip()
		}
		if err != nil {
			return err
		}
		*o = _o
	}

	return nil
}

func (o *MyType) Encode(encoder msgpack.Writer) error {
	if o == nil {
		encoder.WriteNil()
		return nil
	}
	encoder.WriteMapSize(40)
	encoder.WriteString("sameValue")
	o.SameValue.Encode(encoder)
	encoder.WriteString("typeValue")
	o.TypeValue.Encode(encoder)
	encoder.WriteString("stringValue")
	encoder.WriteString(o.StringValue)
	encoder.WriteString("stringOption")
	encoder.WriteNillableString(o.StringOption)
	encoder.WriteString("i64Value")
	encoder.WriteInt64(o.I64Value)
	encoder.WriteString("i64Option")
	encoder.WriteNillableInt64(o.I64Option)
	encoder.WriteString("i32Value")
	encoder.WriteInt32(o.I32Value)
	encoder.WriteString("i32Option")
	encoder.WriteNillableInt32(o.I32Option)
	encoder.WriteString("i16Value")
	encoder.WriteInt16(o.I16Value)
	encoder.WriteString("i16Option")
	encoder.WriteNillableInt16(o.I16Option)
	encoder.WriteString("i8Value")
	encoder.WriteInt8(o.I8Value)
	encoder.WriteString("i8Option")
	encoder.WriteNillableInt8(o.I8Option)
	encoder.WriteString("u64Value")
	encoder.WriteUint64(o.U64Value)
	encoder.WriteString("u64Option")
	encoder.WriteNillableUint64(o.U64Option)
	encoder.WriteString("u32Value")
	encoder.WriteUint32(o.U32Value)
	encoder.WriteString("u32Option")
	encoder.WriteNillableUint32(o.U32Option)
	encoder.WriteString("u16Value")
	encoder.WriteUint16(o.U16Value)
	encoder.WriteString("u16Option")
	encoder.WriteNillableUint16(o.U16Option)
	encoder.WriteString("u8Value")
	encoder.WriteUint8(o.U8Value)
	encoder.WriteString("u8Option")
	encoder.WriteNillableUint8(o.U8Option)
	encoder.WriteString("f64Value")
	encoder.WriteFloat64(o.F64Value)
	encoder.WriteString("f64Option")
	encoder.WriteNillableFloat64(o.F64Option)
	encoder.WriteString("f32Value")
	encoder.WriteFloat32(o.F32Value)
	encoder.WriteString("f32Option")
	encoder.WriteNillableFloat32(o.F32Option)
	encoder.WriteString("datetimeValue")
	encoder.WriteTime(o.DatetimeValue)
	encoder.WriteString("datetimeOption")
	encoder.WriteNillableTime(o.DatetimeOption)
	encoder.WriteString("bytesValue")
	encoder.WriteByteArray(o.BytesValue)
	encoder.WriteString("bytesOption")
	encoder.WriteNillableByteArray(o.BytesOption)
	encoder.WriteString("mapValue")
	encoder.WriteMapSize(uint32(len(o.MapValue)))
	if o.MapValue != nil { // TinyGo bug: ranging over nil maps panics.
		for k, v := range o.MapValue {
			encoder.WriteString(k)
			encoder.WriteInt64(v)
		}
	}
	encoder.WriteString("mapOfTypes")
	encoder.WriteMapSize(uint32(len(o.MapOfTypes)))
	if o.MapOfTypes != nil { // TinyGo bug: ranging over nil maps panics.
		for k, v := range o.MapOfTypes {
			encoder.WriteString(k)
			v.Encode(encoder)
		}
	}
	encoder.WriteString("arrayValue")
	encoder.WriteArraySize(uint32(len(o.ArrayValue)))
	for _, v := range o.ArrayValue {
		encoder.WriteString(v)
	}
	encoder.WriteString("arrayOfTypes")
	encoder.WriteArraySize(uint32(len(o.ArrayOfTypes)))
	for _, v := range o.ArrayOfTypes {
		v.Encode(encoder)
	}
	encoder.WriteString("unionValue")
	o.UnionValue.Encode(encoder)
	encoder.WriteString("unionOption")
	if o.UnionOption == nil {
		encoder.WriteNil()
	} else {
		o.UnionOption.Encode(encoder)
	}
	encoder.WriteString("enumValue")
	encoder.WriteInt32(int32(o.EnumValue))
	encoder.WriteString("enumOption")
	encoder.WriteNillableInt32((*int32)(o.EnumOption))
	encoder.WriteString("aliasValue")
	encoder.WriteString(o.AliasValue.String())
	encoder.WriteString("aliasOption")
	if o.AliasOption == nil {
		encoder.WriteNil()
	} else {
		encoder.WriteString(o.AliasOption.String())
	}
	encoder.WriteString("boolValue")
	encoder.WriteBool(o.BoolValue)
	encoder.WriteString("boolOption")
	encoder.WriteNillableBool(o.BoolOption)

	return nil
}

func (o *MyOtherType) Decode(decoder msgpack.Reader) error {
	numFields, err := decoder.ReadMapSize()
	if err != nil {
		return err
	}

	var _o MyOtherType
	for numFields > 0 {
		numFields--
		field, err := decoder.ReadString()
		if err != nil {
			return err
		}
		switch field {
		case "foo":
			_o.Foo, err = decoder.ReadString()
		case "bar":
			_o.Bar, err = decoder.ReadString()
		default:
			err = decoder.Skip()
		}
		if err != nil {
			return err
		}
		*o = _o
	}

	return nil
}

func (o *MyOtherType) Encode(encoder msgpack.Writer) error {
	if o == nil {
		encoder.WriteNil()
		return nil
	}
	encoder.WriteMapSize(2)
	encoder.WriteString("foo")
	encoder.WriteString(o.Foo)
	encoder.WriteString("bar")
	encoder.WriteString(o.Bar)

	return nil
}

func (o *MyUnion) Decode(decoder msgpack.Reader) error {
	numFields, err := decoder.ReadMapSize()
	if err != nil {
		return err
	}

	var _o MyUnion
	for numFields > 0 {
		numFields--
		field, err := decoder.ReadString()
		if err != nil {
			return err
		}
		switch field {
		case "MyType":
			_o.MyType, err = msgpack.DecodeNillable[MyType](decoder)
		case "MyEnum":
			_o.MyEnum, err = convert.NillableNumeric[MyEnum](decoder.ReadNillableInt32())
		case "string":
			_o.String, err = decoder.ReadNillableString()
		default:
			err = decoder.Skip()
		}
		if err != nil {
			return err
		}
		*o = _o
	}

	return nil
}

func (o *MyUnion) Encode(encoder msgpack.Writer) error {
	if o == nil {
		encoder.WriteNil()
		return nil
	}
	if o.MyType != nil {
		encoder.WriteMapSize(1)
		encoder.WriteString("MyType")
		o.MyType.Encode(encoder)
		return nil
	}
	if o.MyEnum != nil {
		encoder.WriteMapSize(1)
		encoder.WriteString("MyEnum")
		encoder.WriteNillableInt32((*int32)(o.MyEnum))
		return nil
	}
	if o.String != nil {
		encoder.WriteMapSize(1)
		encoder.WriteString("string")
		encoder.WriteNillableString(o.String)
		return nil
	}

	encoder.WriteNil()
	return nil
}
