// Code generated by @apexlang/codegen. DO NOT EDIT.

namespace urlshortener.v1 {

public class MainClass{

    public static void Main(String[] args){
        ShortenerImpl shortener = new ShortenerImpl(new RepositoryImpl());
		}
	}
}