// Code generated by @apexlang/codegen. DO NOT EDIT.

using System;

namespace Urlshortener {
  public class ShortenerImpl : Shortener {
    RepositoryImpl repository = new RepositoryImpl();

    /// Shorten a URL and return a generated identifier.
    public Url Shorten(string url)
    {
      return new Url(); // TODO: Provide implementation.
    }
    /// Return the URL using the generated identifier.
    public Url Lookup(string id)
    {
      return new Url(); // TODO: Provide implementation.
    }
  }
}
