// Code generated by @apexlang/codegen. DO NOT EDIT.

using System;

namespace urlshortener.v1 {
  public class ShortenerImpl : Shortener {

    public ShortenerImpl(RepositoryImpl repository) {}

    // Shorten a URL and return a generated identifier.
    public Url shorten(string url)
    {
      return new Url(); // TODO: Provide implementation.
    }

    // Return the URL using the generated identifier.
    public Url lookup(string id)
    {
      return new Url(); // TODO: Provide implementation.
    }

  }
}
